### DISCUSSION TITLE
Not seeing log after adding a `warn!` statement to debug a dependency

### DISCUSSION THREAD

**Discussion by Teajey** [tokio-rs/tracing#1986] [Q&A] [answered]
I've forked a dependency of my project here and added a `warn!` line to try to see what the code is doing: https://github.com/Teajey/actix-web/commit/7821e35494093244f467b30e96c0881f115c4377

I've overridden the official package with:
```toml
[patch.crates-io]
actix-http = { git = "https://github.com/Teajey/actix-web.git", branch = "debug-headers" }
```

But I'm not seeing this warning in the tracing output of my end application. Is there something obvious that I could be missing that would prevent the log from reaching stdout? I am using `RUST_LOG=debug`.
