### DISCUSSION TITLE
A bit confused about tracing-log `v0.2.0`

### DISCUSSION THREAD

**Discussion by frederikhors** [tokio-rs/tracing#2779] [Q&A] [answered]
I'm a bit confused about tracing-log `v0.2.0`.

I was using 

```toml
tracing = { version = "0.1.40", default-features = false, features = ["log"] }
tracing-appender = { version = "0.2.2", default-features = false }
tracing-log = { version = "0.1.3", default-features = false }
tracing-subscriber = { version = "0.3.17", default-features = false }
```

like this:

```rs
use tracing_log::LogTracer;

//...

LogTracer::init().expect("tracer init");

//...
```

What should I do now with `v0.2.0`?
