### ISSUE TITLE
How support log to console/file? Example not work on published versions...

### ISSUE THREAD

**Issue by mamcx** [tokio-rs/tracing#1179]
I was migrating from slog to tracing and like the overall result, but hit a block when trying to support both  console/file output.

I  find the example https://github.com/tokio-rs/tracing/blob/master/examples/examples/fmt-multiple-writers.rs, but this not compile with last version on crates (0.1.22). So what to do? If I point to the master branch still not compile:

```rust
use tracing_subscriber::{fmt, subscribe::CollectExt, EnvFilter};
   |                               ^^^^^^^^^ could not find `subscribe` in `tracing_subscriber`
```

This is what I have:

```rust
pub fn install_log() {
    let file_appender = tracing_appender::rolling::daily(".", "app.log");
    let (non_blocking, _guard) = tracing_appender::non_blocking(file_appender);

   //This work in 0.1.22 , but how output to both?

    // let subscriber = tracing_subscriber::fmt()
    //     .pretty()
    //     .with_writer(std::io::stdout)
    //     .with_max_level(tracing::Level::DEBUG)
    //     // .with_writer(non_blocking)
    //     .finish();

    let collector = tracing_subscriber::registry()
        .with(EnvFilter::from_default_env().add_directive(tracing::Level::DEBUG.into()))
        .with(fmt::Subscriber::new().with_writer(std::io::stdout))
        .with(fmt::Subscriber::new().with_writer(non_blocking));

    tracing::collect::set_global_default(collector).expect("Unable to set a global collector");
}
```

My crates:

```toml
#tracing="0.1.22"
tracing = { git = "https://github.com/tokio-rs/tracing.git" }
#how switch to https://github.com/tokio-rs/tracing/blob/master/examples/Cargo.toml ?
tracing-futures = "0.2.4"
tracing-appender = "0.1.2"
tracing-log = "0.1.1"
tracing-subscriber = "0.2.15"
```
