### ISSUE TITLE
Annotating functions with `#[tracing::instrument]` does not create spans in tracing-flame

### ISSUE THREAD

**Issue by Wodann** [tokio-rs/tracing#2537]
### Version

```toml
tokio = { version = "1.21.2", default-features = false, features = ["rt-multi-thread", "sync"] }
tracing = { version = "0.1.37", features = ["attributes", "std"], optional = true }
tracing-flame = { version = "0.2.0", default-features = false, features = ["smallvec"] }
tracing-subscriber = { version = "0.3.16", default-features = false, features = ["ansi", "env-filter", "fmt", "parking_lot", "smallvec", "std"] }
```

### Platform

64-bit Windows

### Crates

- tracing
- tracing_flame

### Description

I annotated my functions with the `#[tracing::instrument]` procedural macro. To my understanding, this should create a span for the entire function body.

When I use this in combination with `tracing_flame` to generate a flame chart, none of the functions' spans show up. Only when I add a call to the `tracing::info!`, etc. macros within the tracing-enabled functions, do they show up in the flame graphs.
