### ISSUE TITLE
Allow `tracing_log` log to trace env_logger init from custom env. var

### ISSUE THREAD

**Issue by lcmgh** [tokio-rs/tracing#2766]
Hi!

I'd like to use the log2trace feature but not configured by the default `RUST_LOG` var and rather with a custom one. So I tried to add the env_logger to my dependencies and hoped the `BuilderExt` trait which provides `emit_traces` will then be available but it isn't.

```rust
fn init_log2trace() {
    use tracing_log::log_tracer::Builder;
    use tracing_log::env_logger::BuilderExt;

    env_logger::Builder::from_env("LOG_TO_TRACE")
    .emit_traces()
    .try_init()
}
```

Error

```rust
error[E0599]: no method named `emit_traces` found for struct `env_logger::Builder` in the current scope
   --> core/src/config/log.rs:118:6
    |
117 | /     env_logger::Builder::from_default_env()
118 | |     .emit_traces()
    | |     -^^^^^^^^^^^ method not found in `Builder`
```

I am not sure about the potential solution, maybe env_logger has to be re-exported by `tracing_log`.

Versions:
```toml
tracing = { version = "0.1.37" }
env_logger = "0.10.0"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"],  default-features = false, optional = true }
tracing-log = { version = "0.1.3", features = ["env_logger"], optional = true }
```
