### ISSUE TITLE
made progress on `prune old files at startup`

### ISSUE THREAD

**Issue by qyuzh** [tokio-rs/tracing#3181]
### Version

Latest
### Platform

any
### Crates

tracing_appender
### Description

Has anyone made progress on this feature/fixing - prune old files at startup(#2966). I really need this, thanks.

**Comment by Rolv-Apneseth** [comment]
I think we just need new releases. Using `git` sources for the `tracing`-related crates works for me:

```toml
tracing = { version = "0.1", git = "https://github.com/tokio-rs/tracing.git" }
tracing-subscriber = { features = [
  "env-filter",
], git = "https://github.com/tokio-rs/tracing.git" }
tracing-appender = { version = "0.2", git = "https://github.com/tokio-rs/tracing.git" }
```
