### ISSUE TITLE
`tracing-subscriber`: write spans/events to files

### ISSUE THREAD

**Issue by davidbarsky** [tokio-rs/tracing#407]
### Crates

`tracing-subscriber`should provide guidance for emitting spans/events to a file system, supporting use-cases like file rotation based on set criteria.

### Motivation

I know of people and teams who _could_ use tracing, but they need to log their spans/events to a file system with rotations/max-sizes.

### Proposal

I _think_ the [`with_writer` method](https://docs.rs/tracing-subscriber/0.1.5/tracing_subscriber/fmt/struct.Builder.html#method.with_writer) should be sufficient if coupled with a crate similar to [file-rotate](https://docs.rs/file-rotate/0.1.1/file_rotate/struct.FileRotate.html)—or anything that encapsulates logic for setting up file rotation _and_ implements `std::io::Write`.

**Comment by Kubikx** [comment]
# My use case:
I use `log4rs` that support following message formats: https://docs.rs/log4rs/0.9.0/log4rs/encode/pattern/index.html

my config looks like this: (plus added comments why)
```yml
#refresh_rate: 5 seconds # I uncomment this when I want to change filters at runtime
appenders: # following section contains 2 appenders
  console: # simple write to console
    kind: console
    encoder:
      pattern: "{d(%_H:%M:%S%.3f)(utc)} {h({l})} {I} {M}:{L} {m}{n}" 
      # pattern: "\t{d(%_H:%M:%S%.3f)(utc)} {h({l})} {M}:{L} {n}{m}{n}"

  file: # the more interesting file appender
    kind: once_rolling_file # my own type to roll only once
    path: C:\\Users\\xxxku\\Documents\\BattleForge\\Diag\\_log_proxy_latest.log # this path will always be log from last run (no support for date, or any other variable in file name)
    encoder:
      pattern: "\t{d(%_H:%M:%S%.3f)(utc)} {l} {I} {M}:{L} {n}{m}{n}"
    roller:
      kind: fixed_window # I am using the default roller because it is easier
      pattern: C:\\Users\\xxxku\\Documents\\BattleForge\\Diag\\_log_proxy_{}.log # path that will contains log history  (no support for date in file name), `{}` will be replaced by number
      count: 10 # keep latest plus 10 older logs, so starting game does not delete the log from previous one
      base: 0

root:
  level: info # default filter will be info
  appenders:
    - console
    - file

loggers: # section I use only to filter some messages out
  proxy::networking::sr_packet::from_server::game::GameMessage_ExecuteToStepNotification:
    level: off # this specific module will not emit logs
  proxy:
    level: trace # proxy and all its submodules will use trace as default filter 
```

`once_rolling_file` 
create exactly 1 log file per application start so I know which log to look at, and users know which log to send
My log files are not too big, so I do not need size trigger or anything
it would be interesting to have more options with tracing like roll the file at aplication exit and format date to its name (I was told it would not be hard for you) if easily possible I would like date format customizable because some countries use middle endian date, but I would use something like: `_log_proxy_{d1(%Y.%m.%d)(utc)}-{d2(%Y.%m.%d)(utc)}_{}.log` to have start and stop date in the log name
but rolling at aplication exit expects no fatal crash, so I am not sure if this would be best idea

for the trace formating options I care about the 

- `time` with some formating options, I think log4rs uses chrono for this, so it should not be too hard
- `level` error, warn, info, debug, trace
- `module` from which the trace come (mainly for filtering)
- `line` number of the trace
- `thread id` because I log also threads that are not 'managed' by rust
- `new line` `{n}` in log4rs is important for multiplatform configurations
- `message` of course
- `scope` [spans](https://docs.rs/tracing/0.1.6/tracing/span/index.html) that 'wraps' the trace
- `parameters` (`record key-value fields`)

for the `scope` , and `parameters` I would like simple options to include/exclude them in the output based on criteria.
Right now I created macro that generates modules for each possible packet and based on `level` filter for this module it emit 'detailed', 'simple', or no message. `proxy::networking::sr_packet::from_server::game::GameMessage_ExecuteToStepNotification` this 'ugly' example allow me to filter message `ExecuteToStepNotification` from `GameMessage` type that contains no usefull information, but is received quite often.

For the file access I would expect some simple buffered writer with small buffer.
