### ISSUE TITLE
tracing-subscriber: fmt::SubscriberBuilder::init() log compat doesn't work

### ISSUE THREAD

**Issue by nicholasbishop** [tokio-rs/tracing#489]
The documentation for tracing-subscriber makes it sound like I can convert logging with the `log` crate into logging with the `tracing` crate: https://docs.rs/tracing-subscriber/0.2.0-alpha.2/tracing_subscriber/fmt/struct.SubscriberBuilder.html#method.init

But this is not working for me. Here's my test code:

```rust
fn main() {
    tracing_subscriber::FmtSubscriber::builder()
        .with_max_level(tracing::Level::DEBUG)
        .init();

    tracing::info!("test tracing");
    log::info!("test log");
}
```

And my cargo deps:
```toml
[dependencies]
log = "0.4"
tracing = "0.1"
tracing-subscriber = { version = "0.2.0-alpha", features = ["tracing-log"] }
```

This prints the trace line but not the log line:
```
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/trace-test`
Dec 20 18:14:55.057 INFO trace_test: test tracing
```
